import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from 'next/font/google';


import "./globals.css";
import Navbar from "./ui/navbar";
import { SidebarProvider } from "./contexts/SidebarContext";
import { getSession } from "./auth/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Added '500' for medium emphasis in UI elements
  style: ['normal', 'italic'],   // Included italics for code comments/emphasis
  display: 'swap',
  variable: '--font-poppins',
  fallback: ['system-ui', 'sans-serif'], // Explicit fallbacks reduce layout shift
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession()
  const isLoggedIn = !!session?.token

  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <SidebarProvider>
          <Navbar isLoggedIn={isLoggedIn} />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
